OrdererOrgs:
  - Name: {ORD_NAME0_C}
    Domain: {DOMAIN_NAME}
    Specs:
      - Hostname: {ORD_NAME0}
PeerOrgs:
  - Name: {ORG_1_C}
    Domain: {ORG_1}.{DOMAIN_NAME}
    Template:
      Count: {PCOUNT}
    Users:
      Count: 1
  
  - Name: {ORG_2_C}
    Domain: {ORG_2}.{DOMAIN_NAME}
    Template:
      Count: {PCOUNT}
    Users:
      Count: 1
  
  - Name: {ORG_3_C}
    Domain: {ORG_3}.{DOMAIN_NAME}
    Template:
      Count: {PCOUNT}
    Users:
      Count: 1
